
index: 
	gcc -m32 -Wall -pedantic -g -o ../out/bin/indexdb dataStr/index-db.c dataStr/util.c

query: 
	gcc -m32 -Wall -pedantic -g -o ../out/bin/querydb dataStr/query-with-doclen.c dataStr/query-tools.c dataStr/util.c -lm

hash:
	gcc -m32 -Wall -pedantic -g -o ../out/bin/querydb-hash dataStr/query-with-hash.c dataStr/query-tools.c dataStr/util.c -lm
